### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Andrejki** [TheMrOverload/FacebookAccountGenerator#1]
Hi. Not working.
Best regards. 

andrejki@andrejki:~/Advanced-OSIF/FacebookAccountGenerator$ python3 FBGen.py
Traceback (most recent call last):
  File "/home/andrejki/.local/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Python39\\geckodriver.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "FBGen.py", line 6, in <module>
    driver = webdriver.Firefox(executable_path=r'C:\Python39\geckodriver.exe')
  File "/home/andrejki/.local/lib/python3.8/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/home/andrejki/.local/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'C:\Python39\geckodriver.exe' executable needs to be in PATH.

**Comment by XYZ-Codename** [comment]
put the driver in the directory dumbass
